FROM debian:sid

WORKDIR /opt

RUN apt update
RUN apt install -y npm

RUN npm install -g yarn@1.22.6

COPY package.json package.json
COPY yarn.lock yarn.lock

RUN yarn

COPY . .

RUN yarn build

RUN npm i -g .
