FROM ubuntu:20.10

WORKDIR /opt

RUN apt update
RUN apt install -y npm
RUN apt install -y curl

RUN curl -o- -L https://yarnpkg.com/install.sh | bash

COPY package.json package.json
COPY yarn.lock yarn.lock

RUN yarn

COPY . .

RUN yarn build

RUN npm i -g .
