name: Yarn CI

on: [push, pull_request]

jobs:
  yarn:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies with Yarn
        run: yarn
      - name: Build with make
        run: make -j$(nproc)
      - name: Build with Yarn
        run: yarn build
      - name: Publish to npm
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: pascalgn/npm-publish-action@1.3.5
        with:
          publish_command: "yarn"
          commit_pattern: '.*\:\ Release (\S+)'
          publish_args: "--access public"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish to GitHub pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          CLEAN: true
